# Generated by Django 4.1.2 on 2022-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_films_slug_films_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
