# Generated by Django 4.1.2 on 2022-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_films_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='is_out',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='films',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='films',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='films',
            name='poster',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='films',
            name='rating_imdb',
            field=models.FloatField(blank=True),
        ),
    ]
