# Generated by Django 4.1.2 on 2022-10-30 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_films_is_out_films_is_published_alter_films_imdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='premiere',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
