# Generated by Django 4.1.2 on 2022-11-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
