# Generated by Django 4.1.2 on 2022-11-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_slides_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='url',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
