# Generated by Django 4.1.2 on 2022-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_slides_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
