# Generated by Django 4.1.2 on 2022-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_slides_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'ordering': ['number'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterField(
            model_name='films',
            name='produser',
            field=models.TextField(),
        ),
    ]
